variables:
  CI_IMAGE: $DOCKER_HUB_USER/openwrt
  RELEASE: "19.07.7"

.build:
  image: docker:latest
  stage: build
  services:
   - docker:dind
  before_script:
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_TOKEN
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  script:
    - export OPENWRT_SOURCE_VER=$RELEASE
    - export ARCH=$ARCH
    - export IMAGE=$CI_IMAGE
    - export TAG=${RELEASE}-${ARCH}
    - ./build.sh
    - docker push $CI_IMAGE:${RELEASE}-${ARCH}
  only:
    - master

.build-squashfs:
  extends: .build
  before_script:
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_TOKEN
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    - apk add util-linux fakeroot squashfs-tools

build-release-x86-64:
  extends: .build
  variables:
    ARCH: x86-64

build-release-armvirt-64:
  extends: .build
  variables:
    ARCH: armvirt-64

build-release-armvirt-32:
  extends: .build
  variables:
    ARCH: armvirt-32

build-release-bcm2708:
  extends: .build-squashfs
  variables:
    ARCH: bcm2708

build-snapshot-x86-64:
  extends: .build
  variables:
    ARCH: x86-64
    RELEASE: snapshot

build-snapshot-armvirt-64:
  extends: .build
  variables:
    ARCH: armvirt-64
    RELEASE: snapshot

build-snapshot-armvirt-32:
  extends: .build
  variables:
    ARCH: armvirt-32
    RELEASE: snapshot

build-snapshot-bcm2708:
  extends: .build-squashfs
  variables:
    ARCH: bcm2708
    RELEASE: snapshot
