FROM scratch
COPY . .
ARG ROOT_PW
RUN echo -e "${ROOT_PW}\n${ROOT_PW}" | passwd
RUN mkdir -p /var/lock
RUN opkg update && \
    opkg install \
      iperf3 \
      ip-full && \
    opkg list-upgradable | awk '{print $1}' | xargs opkg upgrade

CMD [ "/sbin/init" ]