FROM scratch
COPY . .
RUN mkdir -p /var/lock
RUN opkg update && \
    opkg install \
      luci \
      iperf3 \
      ip-full
RUN  opkg list-upgradable | awk '{print $1}' | xargs opkg upgrade || true

RUN sed -i '/^exit 0/i cat \/tmp\/resolv.conf > \/etc\/resolv.conf' /etc/rc.local

ARG ts
ARG version
LABEL org.opencontainers.image.created=$ts
LABEL org.opencontainers.image.version=$version
LABEL org.opencontainers.image.source=https://github.com/oofnikj/docker-openwrt

CMD [ "/sbin/init" ]